main: minealex.tmotd.TMOTD
version: 1.4
name: TMOTDBungee

commands:
  motd:
    description: Set the MOTD or reload the configuration.
    usage: /motd set <message> | /motd reload | /motd version